import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "./index.css";
import Cursor from "./components/Cursor";

const afterFont = localFont({
  src: "./fonts/After-Regular.woff", // Font in app/fonts/
  variable: "--font-after",
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${afterFont.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-after)]`}
      >
        <Cursor />
        <div id="cursor-circle"></div>
        {children}
      </body>
    </html>
  );
}
